# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{molo}
  s.version = "0.7.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joel Moss", "Todd Huss", "Michael Grosser"]
  s.date = %q{2010-12-21}
  s.email = %q{joel@developwithstyle.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "Molo.gemspec",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/tasks/molo.rb",
     "spec/molo_spec.rb",
     "vendor/migration_helpers/MIT-LICENSE",
     "vendor/migration_helpers/README.markdown",
     "vendor/migration_helpers/init.rb",
     "vendor/migration_helpers/lib/migration_helper.rb",
     "vendor/rails_sql_views/.gitignore",
     "vendor/rails_sql_views/CHANGELOG",
     "vendor/rails_sql_views/CONTRIB",
     "vendor/rails_sql_views/LICENSE",
     "vendor/rails_sql_views/README",
     "vendor/rails_sql_views/Rakefile",
     "vendor/rails_sql_views/TODO",
     "vendor/rails_sql_views/VERSION",
     "vendor/rails_sql_views/init.rb",
     "vendor/rails_sql_views/lib/active_record/view.rb",
     "vendor/rails_sql_views/lib/core_ext/module.rb",
     "vendor/rails_sql_views/lib/rails_sql_views.rb",
     "vendor/rails_sql_views/lib/rails_sql_views/connection_adapters/abstract/schema_definitions.rb",
     "vendor/rails_sql_views/lib/rails_sql_views/connection_adapters/abstract/schema_statements.rb",
     "vendor/rails_sql_views/lib/rails_sql_views/connection_adapters/abstract_adapter.rb",
     "vendor/rails_sql_views/lib/rails_sql_views/connection_adapters/mysql2_adapter.rb",
     "vendor/rails_sql_views/lib/rails_sql_views/connection_adapters/mysql_adapter.rb",
     "vendor/rails_sql_views/lib/rails_sql_views/connection_adapters/oci_adapter.rb",
     "vendor/rails_sql_views/lib/rails_sql_views/connection_adapters/oracle_adapter.rb",
     "vendor/rails_sql_views/lib/rails_sql_views/connection_adapters/oracleenhanced_adapter.rb",
     "vendor/rails_sql_views/lib/rails_sql_views/connection_adapters/oracleenhanced_adapter.rb.orig",
     "vendor/rails_sql_views/lib/rails_sql_views/connection_adapters/postgresql_adapter.rb",
     "vendor/rails_sql_views/lib/rails_sql_views/connection_adapters/postgresql_adapter.rb.orig",
     "vendor/rails_sql_views/lib/rails_sql_views/connection_adapters/sqlite_adapter.rb",
     "vendor/rails_sql_views/lib/rails_sql_views/connection_adapters/sqlserver_adapter.rb",
     "vendor/rails_sql_views/lib/rails_sql_views/loader.rb",
     "vendor/rails_sql_views/lib/rails_sql_views/schema_dumper.rb",
     "vendor/rails_sql_views/lib/rails_sql_views/version.rb",
     "vendor/rails_sql_views/rails/init.rb",
     "vendor/rails_sql_views/rails_sql_views.gemspec",
     "vendor/rails_sql_views/test/.gitignore",
     "vendor/rails_sql_views/test/README",
     "vendor/rails_sql_views/test/adapter_test.rb",
     "vendor/rails_sql_views/test/connection.example.yml",
     "vendor/rails_sql_views/test/connection/native_mysql/connection.rb",
     "vendor/rails_sql_views/test/connection/native_mysql/schema.sql",
     "vendor/rails_sql_views/test/connection/native_postgresql/connection.rb",
     "vendor/rails_sql_views/test/connection/native_postgresql/schema.sql",
     "vendor/rails_sql_views/test/connection/oracle_enhanced/connection.rb",
     "vendor/rails_sql_views/test/connection/oracle_enhanced/procedures.sql",
     "vendor/rails_sql_views/test/connection/oracle_enhanced/schema.sql",
     "vendor/rails_sql_views/test/models/item.rb",
     "vendor/rails_sql_views/test/models/person.rb",
     "vendor/rails_sql_views/test/models/person2.rb",
     "vendor/rails_sql_views/test/models/place.rb",
     "vendor/rails_sql_views/test/models/v_person.rb",
     "vendor/rails_sql_views/test/models/v_profile.rb",
     "vendor/rails_sql_views/test/schema.native_mysql.expected.rb",
     "vendor/rails_sql_views/test/schema.native_postgresql.expected.rb",
     "vendor/rails_sql_views/test/schema.oracle_enhanced.expected.rb",
     "vendor/rails_sql_views/test/schema_dumper_test.rb",
     "vendor/rails_sql_views/test/test_helper.rb",
     "vendor/rails_sql_views/test/view_model_test.rb",
     "vendor/rails_sql_views/test/view_operations_test.rb",
     "vendor/yaml_db/init.rb",
     "vendor/yaml_db/lib/csv_db.rb",
     "vendor/yaml_db/lib/serialization_helper.rb",
     "vendor/yaml_db/lib/yaml_db.rb",
     "vendor/yaml_db/spec/base.rb",
     "vendor/yaml_db/spec/serialization_helper_base_spec.rb",
     "vendor/yaml_db/spec/serialization_helper_dump_spec.rb",
     "vendor/yaml_db/spec/serialization_helper_load_spec.rb",
     "vendor/yaml_db/spec/serialization_utils_spec.rb",
     "vendor/yaml_db/spec/yaml_dump_spec.rb",
     "vendor/yaml_db/spec/yaml_load_spec.rb",
     "vendor/yaml_db/spec/yaml_utils_spec.rb"
  ]
  s.homepage = %q{http://codaset.com/joelmoss/molo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A thin wrapper to use Rails Migrations in non Rails projects}
  s.test_files = [
    "spec/molo_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["~> 3.0.3"])
      s.add_runtime_dependency(%q<rake>, ["~> 0.8"])
    else
      s.add_dependency(%q<activerecord>, ["~> 3.0.3"])
      s.add_dependency(%q<rake>, ["~> 0.8"])
    end
  else
    s.add_dependency(%q<activerecord>, ["~> 3.0.3"])
    s.add_dependency(%q<rake>, ["~> 0.8"])
  end
end

