# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{molo}
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joel Moss", "Todd Huss", "Michael Grosser"]
  s.date = %q{2010-12-14}
  s.email = %q{joel@developwithstyle.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "Molo.gemspec",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/tasks/molo.rb",
     "spec/molo_spec.rb",
     "vendor/migration_helpers/MIT-LICENSE",
     "vendor/migration_helpers/README.markdown",
     "vendor/migration_helpers/init.rb",
     "vendor/migration_helpers/lib/migration_helper.rb",
     "vendor/yaml_db/init.rb",
     "vendor/yaml_db/lib/csv_db.rb",
     "vendor/yaml_db/lib/serialization_helper.rb",
     "vendor/yaml_db/lib/yaml_db.rb",
     "vendor/yaml_db/spec/base.rb",
     "vendor/yaml_db/spec/serialization_helper_base_spec.rb",
     "vendor/yaml_db/spec/serialization_helper_dump_spec.rb",
     "vendor/yaml_db/spec/serialization_helper_load_spec.rb",
     "vendor/yaml_db/spec/serialization_utils_spec.rb",
     "vendor/yaml_db/spec/yaml_dump_spec.rb",
     "vendor/yaml_db/spec/yaml_load_spec.rb",
     "vendor/yaml_db/spec/yaml_utils_spec.rb"
  ]
  s.homepage = %q{http://codaset.com/joelmoss/molo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A thin wrapper to use Rails Migrations in non Rails projects}
  s.test_files = [
    "spec/molo_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["~> 3.0.3"])
      s.add_runtime_dependency(%q<rake>, ["~> 0.8"])
    else
      s.add_dependency(%q<activerecord>, ["~> 3.0.3"])
      s.add_dependency(%q<rake>, ["~> 0.8"])
    end
  else
    s.add_dependency(%q<activerecord>, ["~> 3.0.3"])
    s.add_dependency(%q<rake>, ["~> 0.8"])
  end
end

